apiVersion: v1
kind: Service
metadata:
  name: ms-usuarios
  namespace: distribuidasms
  labels:
    app: ms-usuarios
spec:
  selector:
    app: ms-usuarios
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
