apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: distrilibreria-ingress
  namespace: distrilibreria
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: distrilibreria.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080

