apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroachdb
  namespace: distri-libreria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 26257
        - containerPort: 8080
        command:
          - "/cockroach/cockroach"
          - "start-single-node"
          - "--insecure"
          - "--store=node1"
          - "--listen-addr=0.0.0.0:26257"
          - "--http-addr=0.0.0.0:8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "100m"
