apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-publicaciones
  namespace: distri-libreria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-publicaciones
  template:
    metadata:
      labels:
        app: ms-publicaciones
    spec:
      containers:
      - name: ms-publicaciones
        image: milenamaldonado/ms-publicaciones:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server-service:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://cockroachdb-service:26257/dbpublicaciones?sslmode=disable"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "admin"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "admin123"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
