apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sincronizacion
  namespace: distri-libreria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-sincronizacion
  template:
    metadata:
      labels:
        app: ms-sincronizacion
    spec:
      containers:
      - name: ms-sincronizacion
        image: milenamaldonado/ms-sincronizacion:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server-service:8761/eureka/"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10

