apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: distri-libreria
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: LoadBalancer

