apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  namespace: distri-libreria
spec:
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  type: ClusterIP

